name: 'Group Pull Requests'
description: 'Groups open Pull requests with a specific label'
inputs:
  target-label:
    description: 'Target label to fetch for PRs'
    required: true
    default: 'stage-ready'
  exclude-current:
    description: 'Whether or not to exclude the current PR target branch'
    default: 'false'
  repo-token:
    description: 'Github token secret'
    required: true
    default: "SECRETTOKEN"
  main-branch:
    description: 'The main branch of the repo'
    default: 'master'
    required: true
  integration-branch:
    description: 'The branch to merge the grouped branches'
    default: 'staging'
    required: true
outputs:
  temp-brancb:
    description: 'Temp branch with all grouped PRs.'
runs:
  using: 'node12'
  main: 'dist/index.js'