name: Pull Request Integrator
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: Deploy on comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Group Open PRs and Merge    
        uses: ./
        id: group-and-merge
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          target-label: stage-ready
          main-branch: 'main'
          integratoin-branch: 'staging'
